name: tmp workflow
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Python version
        run: python --version
      - name: script test
        run: python ${{ github.workspace }}/script/compare_versions.py 1.0.0+1 1.0.0
